port: 13306                     #数据库监听端口
user: root                      #数据库用户
pwd: root                       #数据库密码
autoBakSqlTimeM: 60             #自动备份间隔时间，单位分钟
dataBases: local_game           #自动创建的数据库名称
webPort: 13301                  #用于特殊监听的web端口
